import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  metadataBase: new URL("https://digicompanions.com"),

  title: 'DigiCompanions - 5 Years of Digital Excellence | Foundation Day Celebration',
  description: "Celebrating 5 years of digital marketing excellence. Performance-driven campaigns, trusted by 150+ brands. Join us in building what's next.",
  keywords: 'digital marketing, performance marketing, social media marketing, branding, paid ads, SEO, analytics',

  openGraph: {
    title: 'DigiCompanions - 5 Years of Digital Excellence',
    description: 'Celebrating 5 years of digital marketing excellence. Performance-driven campaigns, trusted by 150+ brands.',
    images: [
      {
        url: '/og-image.jpg', // or your full image path
        width: 1200,
        height: 630,
      },
    ],
  },

  twitter: {
    card: 'summary_large_image',
    title: 'DigiCompanions - 5 Years of Digital Excellence',
    description: 'Celebrating 5 years of digital marketing excellence. Performance-driven campaigns, trusted by 150+ brands.',
    images: ['/og-image.jpg'],
  },
};
  title: 'Create Next App',
  description: 'Generated by create next app',
  openGraph: {
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    images: [
      {
        url: 'https://bolt.new/static/og_default.png',
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
